{"name": "User searches for a keyword", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=51588): Max retries exceeded with url: /session/4d45bc45fb2098c641b06eac9ac6eaa3/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAB57D6E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 18, in after_step\n    screenshot = context.driver.get_screenshot_as_png()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given the user is on the home page", "status": "passed", "attachments": [{"name": "Log", "source": "2ccb8032-36ed-4c4d-8dbc-18c5b84a45fb-attachment.txt", "type": "text/plain"}, {"name": "Step: the user is on the home page", "source": "bb8fdfc3-ed13-44c1-a3ed-77dc4ace084a-attachment.png", "type": "image/png"}], "start": 1722868754119, "stop": 1722868765030}, {"name": "When the user searches for \"Selenium\"", "status": "passed", "attachments": [{"name": "Log", "source": "85624d73-74e7-44f3-ae7b-e898779fab72-attachment.txt", "type": "text/plain"}, {"name": "Log", "source": "1857a4c3-1815-4322-8810-37bd8b68fda5-attachment.txt", "type": "text/plain"}, {"name": "Log", "source": "1a1407e8-058a-42f0-b862-110e0f7a57ba-attachment.txt", "type": "text/plain"}, {"name": "Step: the user searches for \"Selenium\"", "source": "a2ad3a2c-83d5-4f60-96ae-5b5ce9fd6d7b-attachment.png", "type": "image/png"}], "start": 1722868765031, "stop": 1722868768853}, {"name": "Then the search results are displayed", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=51588): Max retries exceeded with url: /session/4d45bc45fb2098c641b06eac9ac6eaa3/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CAB57D6E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 18, in after_step\n    screenshot = context.driver.get_screenshot_as_png()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Shivananda\\Documents\\tryout\\venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "attachments": [{"name": "Log", "source": "2bd56eb0-1b26-4fe1-9b1d-9e9d6b0c75e7-attachment.txt", "type": "text/plain"}], "start": 1722868768853, "stop": 1722868787983}], "start": 1722868751472, "stop": 1722868808433, "uuid": "399375f7-f94d-4250-a165-d05683ec3e78", "historyId": "4f10f50026767b4de3d51ddc3eeb0fe5", "fullName": "Search functionality: User searches for a keyword", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Search functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}